# Configurações do Site
title: "Felipe da Maia Bueno"
# description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Felipe da Maia Bueno"
resume_title:                   "Desenvolvedor Backend"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "felipe_mbsti@hotmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(45)99929-9059"
resume_contact_address:         "Estrada Vila Bendo, Santa Terezinha de Itaipu"

resume_header_contact_info:     "Estrada Vila Bendo, Santa Terezinha de Itaipu • (45)99929-9059 • felipe_mbsti@hotmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Futuro Bacharel em Ciências da Computação, sempre buscando aprender novas tecnologias para
se aperfeiçoar e oferecer o melhor serviço.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/FelipeDaMaiaBueno"
  resume_twitter_url:           "https://twitter.com/DaMaiaBueno"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/felipe.damaiabueno/"
  resume_linkedin_url:          "https://www.linkedin.com/in/felipe-da-maia-bueno-4546b9200/"
  resume_instagram_url:         "https://www.instagram.com/felipedamaiabueno/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
